apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: apps-certificate
spec:
  # Fréquence à laquelle ESO vérifie si le secret a changé dans Vault
  refreshInterval: "1h" 
  
  secretStoreRef:
    name: vault-backend # Doit correspondre au nom du SecretStore
    kind: ClusterSecretStore
    
  target:
    # C'est le nom du Secret Kubernetes RÉEL qui sera généré dans le cluster
    name: apps-certificate
    template:
      type: kubernetes.io/tls # Très important pour que K8s reconnaisse un certificat
      
  data:
    # On fait correspondre les clés de Vault avec les clés attendues par K8s
    - secretKey: tls.crt
      remoteRef:
        key: "hello-app/tls" # Le chemin dans Vault
        property: "tls.crt"                # La clé JSON dans Vault
        
    - secretKey: tls.key
      remoteRef:
        key: "hello-app/tls"
        property: "tls.key"
