resources:
- ../../base

patches:
- target:
    kind: Ingress
    name: hello-app
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: hello-app.apps.symphorines.home
    - op: replace
      path: /spec/tls/0/hosts/0
      value: hello-app.apps.symphorines.home

images:
  - name: registry.example.com/chris7444/hello-app
    newName: zot.symphorines.home/chris7444/hello-app

