apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yaml
  - ingressRoute.yaml
  - apps-certificate-external.yaml

images:
  - name: registry.example.com/chris7444/hello-app
    newName: gitea.symphorines.home/chris/hello-app

