resources:
- ../../base

patches:
- target:
    kind: Ingress
    name: boutique
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: boutique.alp.symphorines.home
    - op: replace
      path: /spec/tls/0/hosts/0
      value: boutique.alp.symphorines.home

