apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- target:
    kind: IngressRoute
    name: argocd-server
  patch: |-
    - op: replace
      path: /spec/routes/0/match
      value: Host(`argocd.rpi.symphorines.home`)
    - op: replace
      path: /spec/routes/1/match
      value:  Host(`argocd.rpi.symphorines.home`) && Header(`Content-Type`, `application/grpc`)

