---
#
# Get status of port in netgear switch
#

#
# Query the switch for all ports sttings
#
- name: query netgear switch
  delegate_to: localhost
  run_once: true
  command:  ntgrrc port settings --address={{ netgear_switch }} --output-format json
  changed_when: False
  register: port_settings_all

#
# Query the switch for POE status of all ports
#
- name: Get POE Power Status
  delegate_to: localhost
  run_once: true
  changed_when: False
  command: ntgrrc poe status --address={{ netgear_switch }} --output-format json
  register: poe_status_all

- name: Display Port status
  delegate_to: localhost
  run_once: true
  vars:
    poe_data: "{{ poe_status_all.stdout | from_json  }}"
    port_data: "{{ port_settings_all.stdout | from_json  }}"
    port_status: "{{ port_data.port_settings[ hostvars[item].switch_port  - 1 ]['Port Status']}}"
    port_name:   "{{ port_data.port_settings[ hostvars[item].switch_port  - 1 ]['Port Name']}}"
    port_id:     "{{ port_data.port_settings[ hostvars[item].switch_port  - 1 ]['Port ID']}}"
    poe_status:  "{{ poe_data.poe_status[  hostvars[item].switch_port  - 1 ]['Status'] }}"
  debug:
    msg: "Port {{ port_id }} ( {{ port_name }}) is {{ port_status }} Power Status: {{ poe_status }} "
  with_items: 
  - "{{ ansible_play_hosts }}"
