---
#
# Get an Admin Token to query the switch
#
  - name: login netgear switch
    delegate_to: localhost
    run_once: True
    command: ntgrrc login --address={{ netgear_switch }} --password {{ netgear_admin_password }}
    register: result
    changed_when: False
    failed_when: False

  - fail:
    when: result.rc != 0 and
          'login request returned 200 OK' not in result.stdout

  - name: Debug
    delegate_to: localhost
    run_once: True
    debug:
      msg: "Login succeeded"

