---
#
# netgear specific actions including
#   login
#   poweron port
#   poweroff port
#

- include_tasks: prereqs.yaml

- include_tasks: login.yaml

- include_tasks: poweroff.yaml
  when: poweroff is defined

- include_tasks: poweron.yaml
  when: poweron is defined

- include_tasks: getstatus.yaml
  when: getstatus is defined
