---
- name: Enable required cgroup features.
  become: true
  lineinfile:
    path: /boot//firmware/cmdline.txt
    backrefs: True
    regexp: '(^.+rootwait(\s+(?!cgroup_memory=1 cgroup_enable=memory)[\w=/\-\.]+)*)\s*$'
    line: '\1 cgroup_memory=1 cgroup_enable=memory'
    state: present
  register: cgroup_features

- name: Reboot immediately if cgroup feature changed
  become: true
  ansible.builtin.reboot:
  register: res
  when: cgroup_features is changed

- name: Report
  debug: var=res
  when: cgroup_features is changed

