---
# See https://raspberrypi.stackexchange.com/q/84390/6506
- name: Disable swap.
  become: true
  shell: |
    dphys-swapfile swapoff
    dphys-swapfile uninstall
    update-rc.d -f dphys-swapfile remove
    apt purge -y dphys-swapfile
  when:
    - ansible_swaptotal_mb > 0
