---
- name: Install azlux.fr gpg key
  become: true
  ansible.builtin.get_url:
    url: https://azlux.fr/repo.gpg
    dest: /usr/share/keyrings/azlux-archive-keyring.gpg

- name: Install the azlux repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/azlux-archive-keyring.gpg] http://packages.azlux.fr/debian/ {{ ansible_distribution_release }} main"
    filename: azlux
    state: present

- name: install log2ram
  become: true
  ansible.builtin.apt:
    name: log2ram
    update_cache: yes
    state: present
