- name: Add log2ram repo
  become: true
  apt_repository:
    repo:  deb http://packages.azlux.fr/debian/ buster main
    state: present

- name: Add gpg key
  become: true
  apt_key:
    url: https://azlux.fr/repo.gpg.key
    state: present

- name: install log2ram
  become: true
  apt:
    name: log2ram
    update_cache: yes
    state: present
