---
#
# Install or Update k3s on a master node
#
- hosts: master
  gather_facts: yes
  tasks:

  - name: Determine version released in 'stable' channel
    shell: |
      version_url=https://update.k3s.io/v1-release/channels/stable
      VERSION_K3S=$(curl -w '%{url_effective}' -L -s -S ${version_url} -o /dev/null | sed -e 's|.*/||')
      echo ${VERSION_K3S}
    changed_when: false
    register: res_stable_version

  - name: Determine current version of k3s
    shell: |
      k3s --version | grep k3s | awk '{print $3}'
    changed_when: false
    failed_when: false
    register: res_current_version

  - set_fact:
      update_needed: "{{ current_version != stable_version }}"
    vars:
      stable_version: "{{ res_stable_version.stdout_lines[0] | default('stable_undefined') }}"
      current_version: "{{ res_current_version.stdout_lines[0] | default('current_undefined') }}"

  - name: Update all hosts (Alpine)
    become: true
    ansible.builtin.apk:
      update_cache: true
      upgrade: yes
    when:
    - ansible_os_family == "Alpine"
    - update_needed

  - name: Update all hosts (Debian)
    become: true
    ansible.builtin.apt:
      update_cache: true
      upgrade: full
    when:
    - ansible_os_family == "Debian"
    - update_needed

  - name: Ensure the directory /usr/local/bin directory exists
    become: true
    file:
      path: /usr/local/bin  # The path of the directory to create
      state: directory
    when:
    - update_needed

  - name: Install k3s Server
    become: true
    shell: |
       curl -sfL https://get.k3s.io | sh -
    when:
    - update_needed

  - name: retrieve k3s.yaml
    become: true
    fetch: 
      src: /etc/rancher/k3s/k3s.yaml
      dest: "{{ lookup('env','HOME') }}/k3s.yaml"
      flat: yes
    when:
    - update_needed
