---
#
# Shutdown all nodes
#
- hosts: master:worker
  gather_facts: no
  vars_files:
  - secrets.yaml

  tasks:
  - include_tasks: tasks/shutdown.yaml
  - include_tasks: tasks/poweroff.yaml
    when: netgear_switch is defined
