---
#
# Shutdown all nodes
#
- hosts: master:worker
  gather_facts: no
  vars_files:
  - secrets.yaml

  tasks:
  - include_tasks: tasks/shutdown.yaml

#
# Poweroff nodes
#
- hosts: master:worker
  gather_facts: no
  vars_files:
  - secrets.yaml
  roles:
  - role: netgear
    vars:
      poweroff: True
    when: netgear_switch is defined
