- hosts: all
  gather_facts: no
  tasks:
  - name: Pies temperature
    become: true
    changed_when: False
    shell: |
      /usr/bin/vcgencmd measure_temp
    register: temp
  - debug: var=temp.stdout_lines[0]
