apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://vault.symphorines.home:8200"
      caProvider:
        type: Secret
        name: vault-ca-cert
        key: ca.crt
        namespace: external-secrets
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: kub-apps
          role: "eso-role"
          serviceAccountRef:
            name: "external-secrets"
            namespace: "external-secrets"
