secretGenerator:
- name: apps-certificate
  files:
  - secrets/tls.crt
  - secrets/tls.key
  type: "kubernetes.io/tls"

namespace: whoami

resources:
- namespace.yaml
- route.yaml
- workload.yaml
- middlewares.yaml
