#!/bin/bash

kubectl -n kubernetes-dashboard get svc kubernetes-dashboard -o name
if [ $? != 0 ]
then
  echo Deploying the Kubernetes Dashboard
  kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/recommended.yaml
fi

#
# Create the Admin user
#
cat <<EOF >/tmp/admin-user.yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-user
  namespace: kubernetes-dashboard

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: admin-user
  namespace: kubernetes-dashboard

EOF
kubectl apply -f /tmp/admin-user.yaml

#
# retrieve the token
#
admin_user_token=$(kubectl -n kubernetes-dashboard get secret | grep admin-user | awk '{print $1}')
token=$(kubectl get secret -n kubernetes-dashboard $admin_user_token -o json | jq -r .data.token | base64 -d )
echo token=$token

