resources:
- ../../base
patches:
- target:
    kind: Ingress
    name: hello-app
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: hello-app.alp.symphorines.home
    - op: replace
      path: /spec/tls/0/hosts/0
      value: hello-app.alp.symphorines.home
