apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: whoami
  namespace: whoami
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`whoami.apps.symphorines.home`)
    services:
    - name: whoami
      port: 80
  tls:
    secretName: apps-tls-secret
